### ISSUE TITLE
What is up with the name?

### ISSUE THREAD

**Issue by brunnerh** [michaelficarra/proposal-iterator-unique#4]
To my knowledge "uniq" is not a word, is this another `flat`/`flatMap` situation?

**Comment by ljharb** [comment]
it's a common shortening of "unique".

**Comment by brunnerh** [comment]
I am aware, but unless there is a name conflict, this makes no sense to me.
What value is there in doing this? Save two characters?

I know that `Math` e.g. is full of abbreviations but generally JS does not do this.
Consider e.g. `queueMicrotask` or `requestAnimationFrame` for reference.

`Array` and `Iterator` currently do not have abbreviated methods, it would be inconsistent and confusing to add such a method unless there is a good reason to do so.

**Comment by michaelficarra** [comment]
This proposal is at stage 1. Details, including the function name, have not yet been decided. Any code examples you may have seen are just that: examples. They have to use *some* name to talk about the function. `uniq` is a candidate because of [prior art](https://github.com/tc39/proposal-iterator-unique#prior-art) that uses that name. Your feedback on this choice is acknowledged.

> I know that `Math` e.g. is full of abbreviations but generally JS does not do this.
> Consider e.g. `queueMicrotask` or `requestAnimationFrame` for reference.

`queueMicrotask` and `requestAnimationFrame` are not part of the JavaScript standard library. `Math` is.

**Comment by brunnerh** [comment]
> Details, including the function name, have not yet been decided.

The read-me heading "chosen solution" then sounds maybe a bit too definitive.

There is another issue with the name given there:
The suffix `By` implies an argument, but it's optional.

> ```js
> let uniques = iter.uniqBy();
> let uniques = iter.uniqBy(obj => obj.field);
> ```

I would suggest using either `unique` or `distinct` if a single function is used rather than two separate ones.

```js
let uniques = iter.unique();
let uniques = iter.unique(obj => obj.field);

let uniques = iter.distinct();
let uniques = iter.distinct(obj => obj.field);
```
